-- RAYAN ONLINE EXHIBITION v4
-- Shared guestbook + check-in wall (hardened public demo setup)

create table if not exists public.guestbook (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 24),
  favorite text,
  message text not null check (char_length(message) between 1 and 140),
  ticket_no text,
  created_at timestamptz not null default now()
);

create table if not exists public.checkins (
  id bigint generated by default as identity primary key,
  name text check (name is null or char_length(name) <= 24),
  ticket_no text,
  image_url text not null,
  created_at timestamptz not null default now()
);

alter table public.guestbook enable row level security;
alter table public.checkins enable row level security;

-- Least-privilege table grants for browser clients.
revoke all on table public.guestbook from anon, authenticated;
revoke all on table public.checkins from anon, authenticated;
grant select, insert on table public.guestbook to anon, authenticated;
grant select, insert on table public.checkins to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

drop policy if exists "guestbook public read" on public.guestbook;
create policy "guestbook public read" on public.guestbook
for select to anon using (true);

drop policy if exists "guestbook public insert" on public.guestbook;
create policy "guestbook public insert" on public.guestbook
for insert to anon with check (
  char_length(name) between 1 and 24 and
  char_length(message) between 1 and 140
);

drop policy if exists "checkins public read" on public.checkins;
create policy "checkins public read" on public.checkins
for select to anon using (true);

drop policy if exists "checkins public insert" on public.checkins;
create policy "checkins public insert" on public.checkins
for insert to anon with check (
  image_url like 'https://%'
);

-- Public bucket so finished check-in cards can be displayed by URL.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('checkins', 'checkins', true, 3145728, array['image/png']::text[])
on conflict (id) do update
set public = true,
    file_size_limit = 3145728,
    allowed_mime_types = array['image/png']::text[];

drop policy if exists "checkins bucket upload" on storage.objects;
create policy "checkins bucket upload" on storage.objects
for insert to anon with check (
  bucket_id = 'checkins' and
  lower(storage.extension(name)) = 'png'
);

-- Do not add a broad SELECT policy on storage.objects for this public bucket.
-- Known public object URLs are already readable, while omitting SELECT prevents listing.
drop policy if exists "checkins bucket public read" on storage.objects;
